haproxy:
  extends:
    file: haproxy.yml
    service: haproxy-server
  links:
    - web
# only needed for dockercon demo
#  environment:
#   - "constraint:node==swarm-0"
web:
  image: alvinr/demo-webapp
  extends:
    file: haproxy.yml
    service: haproxy-app
  links:
    - mongodb
  environment:
    - MONGO_HOST=prod_mongodb_1
mongodb:
  image: mongo
# only needed for dockercon demo
#  environment:
#    - "constraint:node==swarm-0"
  command: --smallfiles --noprealloc
